/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KkBadge {
        /**
          * Type of the badge.
         */
        "type": 'info' | 'warning' | 'success' | 'error';
    }
    interface KkButton {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLKkBadgeElement extends Components.KkBadge, HTMLStencilElement {
    }
    var HTMLKkBadgeElement: {
        prototype: HTMLKkBadgeElement;
        new (): HTMLKkBadgeElement;
    };
    interface HTMLKkButtonElement extends Components.KkButton, HTMLStencilElement {
    }
    var HTMLKkButtonElement: {
        prototype: HTMLKkButtonElement;
        new (): HTMLKkButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "kk-badge": HTMLKkBadgeElement;
        "kk-button": HTMLKkButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KkBadge {
        /**
          * Type of the badge.
         */
        "type"?: 'info' | 'warning' | 'success' | 'error';
    }
    interface KkButton {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "kk-badge": KkBadge;
        "kk-button": KkButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kk-badge": LocalJSX.KkBadge & JSXBase.HTMLAttributes<HTMLKkBadgeElement>;
            "kk-button": LocalJSX.KkButton & JSXBase.HTMLAttributes<HTMLKkButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
